In [1]:
import tensorflow as tf
import numpy as np

In [19]:
input=tf.placeholder(tf.float32, (5,))
w=tf.Variable(np.random.uniform(size=(5,)), dtype=tf.float32)
b=tf.zeros_like(input)
o=input*w+b
label=tf.placeholder(np.float32, (5,))
loss=tf.losses.mean_squared_error(o, label)
grads=tf.gradients(loss, [w,b])

In [20]:
sess=tf.InteractiveSession()
sess.run(tf.global_variables_initializer())

In [21]:
inp=np.float32(np.random.randint(10, size=(5,)))
lbl=np.float32(np.random.randint(10, size=(5,)))

In [22]:
results=sess.run([o-label, grads], feed_dict={input:inp, label:lbl})

In [23]:
results[0]

array([-5.668618  , -2.136104  ,  4.4964743 ,  0.01105642, -5.        ],
      dtype=float32)

In [24]:
results[1][1]

array([-2.2674472 , -0.85444164,  1.7985897 ,  0.00442257, -2.        ],
      dtype=float32)

In [25]:
results[0]*(2/5)

array([-2.2674472 , -0.85444164,  1.7985897 ,  0.00442257, -2.        ],
      dtype=float32)

In [26]:
writer=tf.summary.FileWriter('/tmp/test', sess.graph)